version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/fontend"
      schedule:
          interval: "weekly"

    - package-ecosystem: "gomod"
      directory: "/import"
      schedule:
          interval: "weekly"
