name: release

on:
    push:
        tags:
            - "*"
      
jobs:
    test_release:
        name: release
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: build node
              working-directory: frontend
              run: | 
                npm ci
                npm run build
            - name: Zip Frontend
              run: zip -r ./frontend.zip ./frontend/build
            - name: Zip Backend
              run: zip -r ./backend.zip ./backend
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                files: |
                  backend.zip
                  frontend.zip