name: test release

on:
    check_run:
      
jobs:
    test_release:
        name: Test release
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: build node
              working-directory: frontend
              run: | 
                npm ci
                npm run build
            - name: Zip Frontend
              run: (cd ./frontend/build && zip -q -r - .) > frontend.zip
            - name: Zip Backend
              run: (cd ./backend && zip -q -r - .) > backend.zip
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                  backend.zip
                  frontend.zip