name: test build

on:
  push:
    branches:
      - main
      - "dependabot/npm_and_yarn**"

permissions:
  contents: write

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "lts"
          cache: true
      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -rf pnpm-lock.yaml
          vp i
      - run: vp check
      - run: vp build
